name: demirli_tech
description: Demirli Tech Website

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  url_strategy: ^0.2.0
  flutter_bloc: ^8.1.2
  carousel_slider: ^4.2.0
  url_launcher: ^6.1.7
  google_fonts: ^4.0.1
  web_smooth_scroll: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.11.0"

flutter_icons:
  web:
    generate: true
    image_path: "assets/images/logo/demirli_tech_only_logo_web_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/images/badges/
    - assets/images/contact/
    - assets/images/logo/
    - assets/images/product/
    - assets/images/product/kost/
    - assets/images/product/planok/
    - assets/images/product/qr_projem/
    - assets/images/product/reb_ar/
    - assets/images/service/
